# Generated by Django 4.1.7 on 2023-03-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo_list',
            options={'ordering': ['is_complete']},
        ),
        migrations.RemoveField(
            model_name='todo_list',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='todo_list',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo_list',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
