# Generated by Django 4.1.7 on 2023-03-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_todo_list_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_list',
            name='is_complete',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
